In [1]:
import numpy as np

Задание 1

In [2]:
a = np.array([[1,6], [2,8], [3,11], [3,10], [1,7]])

In [16]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
type(a)

numpy.ndarray

In [22]:
mean_a =  np.mean(a, axis = 0)

In [35]:
mean_a

array([2. , 8.4])

Задание 2

In [46]:
a_centered = np.array([a[0]-mean_a, a[1]-mean_a, a[2]-mean_a, a[3]-mean_a, a[4]-mean_a])

In [47]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [48]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [49]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

Задание 5

In [50]:
np.cov(a.T)[0, 1]

2.0